apiVersion: v1
data:
  index.html: |+
    <!DOCTYPE html>
    <html>
    <head>
    <title>Hello World</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Hello World</h1>
    <p><em>Thank you</em></p>
    </body>
    </html>

kind: ConfigMap
metadata:
  name: nginx-index-html-configmap
